version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27027:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hcmute
      MONGO_INITDB_ROOT_PASSWORD: hcmute
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: hcmute
      ME_CONFIG_MONGODB_ADMINPASSWORD: hcmute
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    ports:
      - "8181:8080"
    environment:
      KEYCLOAK_USER: hcmute
      KEYCLOAK_PASSWORD: hcmute
#  springboot-app:
#    image: springboot
#    container_name: springboot-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongodb
#    environment:
#      SPRING_DATA_MONGODB_URI: mongodb://hcmute:hcmute@mongodb:27017/user
